### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by floyd-fuh** [kcwu/afl-kit#3]
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/afl-kit/afl-cmin.py", line 193, in run
    if idx < m[t]:
IndexError: array index out of range

**Comment by kcwu** [comment]
What version of AFL did you use? Have you locally modified `MAP_SIZE` of AFL?

It would be helpful to debug if you can attach the output of afl-showmap.
(Run afl-cmin.py with `--debug` once, see how `afl-showmap` is called.)

**Comment by fgeek** [comment]
@floyd-fuh could you provide more information?

**Comment by floyd-fuh** [comment]
This was quiet some time ago... I didn't locally modified the MAP_SIZE. I haven't used afl-kit much since, but I was definitely running on ARM when I got this error and I was afl-cmin big corpuses. I thought it would be a really easy one to fix (check if t is in the range of m) so that's why my issue report was so short. My bad. So I'm really sorry I can't provide any more info here. 

But, what I would suggest if you really want to fix this error for sure is to add a check that would catch this error and print a message to the screen that the reproducing steps should please be posted here. So at least the next one who runs into this issue can report it. Whoever runs afl-kit should be skilled enough to post to a github issue. But that's just an idea, it is completely up to you guys. Closing as "can't reproduce" is fine, too.

**Comment by kcwu** [comment]
Close as unreproducible. BTW, I made it support `AFL_MAP_SIZE` env variable.
