### ISSUE TITLE
Ressource limiting

### ISSUE THREAD

**Issue by floyd-fuh** [kcwu/afl-kit#4]
I just wanted to add that in situations where a lot of forking is going on and ressources used (RAM), afl-cmin.py gets killed by the system, whereas in afl-cmin it only kills the child processes for some reason. I just ran into this problem. So you might want to think about further process ressource limitations.

**Comment by kcwu** [comment]
I'm wondering, what is the real issue to fix.
1. afl-cmin.py generates too much loads (forks and eat memory). Is smaller `-w` helpful? 
For this case, I may need to use less aggressive value for default number of worker. Or implement other improvements to reduce memory usage.

2. Instead, you want afl-cmin.py can handle failure cases gracefully in high loading (no matter loading generated by afl-cmin.py or any other programs).

Could you clarify your expectation? And it would be great if you can share some numbers of your system (memory size, how many files, how much ram does your target need, how many workers do you use, etc.)

**Comment by floyd-fuh** [comment]
Hi,

I think number 1 is what I had in mind. But you are right, maybe I should have tried a different -w, but I didn't. I only ran into this problem once yet, I'll get back to you with more details when I run into it again. For now I can only provide that I have a Odroid u3 system (see specs at http://www.hardkernel.com/main/products/prdt_info.php?g_code=G138745696275&tab_idx=2 ). I'll reopen this issues (or a new one) as soon as I can provide more details.
